version: '3.3'
services:
  php_app:
    build: ./
    volumes:
      - ./:/usr/share/nginx/html/api
    depends_on: 
      - database
  web:
    image: nginx:alpine
    depends_on: 
      - php_app
    ports: 
      - 8899:80
    volumes:
      # - ./:/usr/share/nginx/html/api:rw
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
    # - NGINX_HOST=foobar.com
    - NGINX_PORT=80


  database:
    image: mysql:5.7
    volumes: 
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wujian
      - MYSQL_DATABASE=data_system
      - MYSQL_USER=wujian
      - MYSQL_PASSWORD=wujian
    ports: 
      - 3306:3306

volumes:
  dbdata: 